# Generated by Django 5.1.2 on 2024-11-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_permission_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(default='https://m.imooc.com/static/wap/static/common/img/logo-small@2x.png', help_text='用户头像', max_length=200, verbose_name='用户头像'),
        ),
    ]
