# Generated by Django 5.1.2 on 2024-11-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.CharField(help_text='内容', max_length=2000, null=True, verbose_name='内容'),
        ),
    ]
